### PR TITLE
Update TikTok API

### PR DESCRIPTION
**Pull request by Evil0ctal**

### CODE REVIEW

**Review by Tairraos — APPROVED** [review]

**Comment by Tairraos** [comment]
Thanks for updating API。

**Comment by Tairraos** [comment]
After I merged your PR, the new API still can't work. As i test, There returned empty from new API.

**Comment by Evil0ctal** [comment]
> After I merged your PR, the new API still can't work. As i test, There returned empty from new API.

The new API is tested and work
https://api.douyin.wtf/api?url=https://www.tiktok.com/t/ZTdE3d4m6/?k=1
https://api.tiktokv.com/aweme/v1/aweme/detail/?aweme_id=7082200610367360283
Check my repo:
https://github.com/Evil0ctal/Douyin_TikTok_Download_API

**Comment by Tairraos** [comment]
Can I have your wechat to have efficient talk?
image

**Comment by Evil0ctal** [comment]
> Can I have your wechat to have efficient talk? image

Ok

**Comment by Tairraos** [comment]
I got the reason. need remove [ ] from old API.

**Pull request merged**
